package com.healthaggregator.ai

import com.healthaggregator.data.dao.ChatDao
import com.healthaggregator.data.dao.LabDao
import com.healthaggregator.data.entities.LabObservation
import java.time.Instant
import java.time.ZoneId
import java.time.ZoneOffset
import java.time.format.DateTimeFormatter
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class ChatExporter @Inject constructor(
	private val chat: ChatDao,
	private val labs: LabDao,
) {
	suspend fun exportMarkdown(conversationId: String, now: Instant = Instant.now()): String {
		val c = chat.getConversation(conversationId) ?: error("conversation not found")
		val messages = chat.messagesSnapshot(conversationId)
		val labIndex: Map<Pair<String, String>, LabObservation> =
			labs.getAllSnapshot().associateBy { it.sourceSystem to it.fhirReference }

		return buildString {
			appendLine("# ${c.title}")
			appendLine()
			appendLine("_Exported ${fmt(now)} — model ${c.modelId}_")
			appendLine()
			appendLine("---")
			appendLine()
			appendLine("**This is not medical advice.** The assistant is an analytical aid. Verify all findings with a licensed clinician before acting on them.")
			appendLine()
			appendLine("---")
			appendLine()

			for (m in messages) {
				if (m.role == "user") {
					appendLine("### You")
					appendLine()
					appendLine(m.content)
					appendLine()
				}
				if (m.role == "assistant" && m.content.isNotBlank()) {
					appendLine("### Assistant")
					appendLine()
					appendLine(resolveCitations(m.content, labIndex))
					appendLine()
				}
			}

			appendLine("---")
			appendLine()
			appendLine("_Generated by HealthAggregator AI Assistant._")
		}
	}

	suspend fun exportPdf(conversationId: String, now: Instant = Instant.now()): ByteArray {
		val markdown = exportMarkdown(conversationId, now)
		return markdownToPdfBytes(markdown)
	}

	private fun markdownToPdfBytes(markdown: String): ByteArray {
		val doc = android.graphics.pdf.PdfDocument()
		val pageWidth = 612
		val pageHeight = 792
		val margin = 48
		val lineHeight = 14f
		val maxLinesPerPage = ((pageHeight - 2 * margin) / lineHeight).toInt()

		val paint = android.graphics.Paint().apply {
			textSize = 10f
			color = android.graphics.Color.BLACK
		}
		val headerPaint = android.graphics.Paint(paint).apply {
			textSize = 12f
			isFakeBoldText = true
		}

		val wrapWidth = pageWidth - 2 * margin
		val allLines = mutableListOf<Pair<Boolean, String>>()
		markdown.lineSequence().forEach { raw ->
			val isHeader = raw.startsWith("#")
			val stripped = raw.trimStart('#').trim()
			val wrapped = wrap(if (isHeader) stripped else raw, if (isHeader) headerPaint else paint, wrapWidth)
			wrapped.forEach { allLines.add(isHeader to it) }
		}

		var pageNumber = 1
		var lineIndex = 0
		while (lineIndex < allLines.size) {
			val pageInfo = android.graphics.pdf.PdfDocument.PageInfo.Builder(pageWidth, pageHeight, pageNumber).create()
			val page = doc.startPage(pageInfo)
			val canvas = page.canvas
			var y = margin.toFloat() + lineHeight
			var linesOnPage = 0
			while (linesOnPage < maxLinesPerPage && lineIndex < allLines.size) {
				val (isHeader, line) = allLines[lineIndex]
				canvas.drawText(line, margin.toFloat(), y, if (isHeader) headerPaint else paint)
				y += lineHeight
				linesOnPage++
				lineIndex++
			}
			doc.finishPage(page)
			pageNumber++
		}

		val out = java.io.ByteArrayOutputStream()
		doc.writeTo(out)
		doc.close()
		return out.toByteArray()
	}

	private fun wrap(text: String, paint: android.graphics.Paint, maxWidth: Int): List<String> {
		if (text.isEmpty()) return listOf("")
		val words = text.split(" ")
		val lines = mutableListOf<String>()
		var current = StringBuilder()
		for (word in words) {
			val candidate = if (current.isEmpty()) word else "$current $word"
			if (paint.measureText(candidate) <= maxWidth) {
				if (current.isEmpty()) current.append(word) else current.append(' ').append(word)
			} else {
				if (current.isNotEmpty()) lines.add(current.toString())
				current = StringBuilder(word)
			}
		}
		if (current.isNotEmpty()) lines.add(current.toString())
		return lines
	}

	private fun resolveCitations(text: String, index: Map<Pair<String, String>, LabObservation>): String {
		val segments = CitationRenderer.parse(text)
		return buildString {
			segments.forEach { seg ->
				when (seg) {
					is CitationSegment.Text -> append(seg.text)
					is CitationSegment.Cite -> {
						val lab = index[seg.sourceSystem to seg.fhirRef]
						if (lab != null) {
							val date = lab.effectiveAt?.let { dateOnly(it) } ?: "n/a"
							val value = lab.numericValue?.let { "$it ${lab.unit ?: ""}" }?.trim() ?: (lab.textValue ?: "—")
							append("[$value on $date, ${lab.sourceName}]")
						} else {
							append("[${seg.sourceSystem}/${seg.fhirRef}]")
						}
					}
				}
			}
		}
	}

	private fun fmt(i: Instant): String =
		DateTimeFormatter.ofPattern("MMM d, yyyy HH:mm z").withZone(ZoneId.systemDefault()).format(i)

	private fun dateOnly(i: Instant): String =
		DateTimeFormatter.ISO_LOCAL_DATE.format(i.atOffset(ZoneOffset.UTC).toLocalDate())
}
