// <auto-generated />
using System;
using HealthAggregator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthAggregator.Data.Migrations
{
    [DbContext(typeof(HealthAggregatorDbContext))]
    [Migration("20260414205413_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("HealthAggregator.Data.Entities.AiMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AiThreadId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AiMessages");
                });

            modelBuilder.Entity("HealthAggregator.Data.Entities.AiThread", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AiThreads");
                });

            modelBuilder.Entity("HealthAggregator.Data.Entities.AllergyRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllergyText")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClinicalStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("FhirReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientFhirId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceSystem", "FhirReference")
                        .IsUnique();

                    b.ToTable("Allergies");
                });

            modelBuilder.Entity("HealthAggregator.Data.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("HealthAggregator.Data.Entities.ConditionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClinicalStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodeText")
                        .HasColumnType("TEXT");

                    b.Property<string>("FhirReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("OnsetAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientFhirId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceSystem", "FhirReference")
                        .IsUnique();

                    b.ToTable("Conditions");
                });

            modelBuilder.Entity("HealthAggregator.Data.Entities.DiagnosticReportRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeText")
                        .HasColumnType("TEXT");

                    b.Property<string>("FhirReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("IssuedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientFhirId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultReferences")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceSystem", "FhirReference")
                        .IsUnique();

                    b.ToTable("DiagnosticReports");
                });

            modelBuilder.Entity("HealthAggregator.Data.Entities.DocumentRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DocumentedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FhirReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientFhirId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeText")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceSystem", "FhirReference")
                        .IsUnique();

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("HealthAggregator.Data.Entities.EncounterRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FhirReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientFhirId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeText")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceSystem", "FhirReference")
                        .IsUnique();

                    b.ToTable("Encounters");
                });

            modelBuilder.Entity("HealthAggregator.Data.Entities.EpicAuthorizationState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeVerifier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Consumed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RedirectUri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("State")
                        .IsUnique();

                    b.ToTable("EpicAuthorizationStates");
                });

            modelBuilder.Entity("HealthAggregator.Data.Entities.EpicConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ConnectedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FhirBaseUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId")
                        .IsUnique();

                    b.ToTable("EpicConnections");
                });

            modelBuilder.Entity("HealthAggregator.Data.Entities.LabObservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiagnosticReportReference")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EffectiveAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FhirReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Interpretation")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoincCode")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NumericValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientFhirId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ReferenceHigh")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ReferenceLow")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceText")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TextValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LoincCode", "EffectiveAt");

                    b.HasIndex("SourceSystem", "FhirReference")
                        .IsUnique();

                    b.ToTable("LabObservations");
                });

            modelBuilder.Entity("HealthAggregator.Data.Entities.MedicationRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("AuthoredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FhirReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MedicationText")
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientFhirId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceSystem", "FhirReference")
                        .IsUnique();

                    b.ToTable("Medications");
                });

            modelBuilder.Entity("HealthAggregator.Data.Entities.PatientRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FhirId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceSystem", "FhirId")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("HealthAggregator.Data.Entities.SourceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FhirReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SyncJobId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceSystem", "ResourceType", "ResourceId")
                        .IsUnique();

                    b.ToTable("SourceRecords");
                });

            modelBuilder.Entity("HealthAggregator.Data.Entities.SyncJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<int>("LabObservationsUpserted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceRecordsUpserted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SyncJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
